#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

char kennzeichen[723][500]={"A-Stadt Augsburg  Landkreis Augsburg	",
                                    "AA-Ostalbkreis	"	,
                                    "AB-Stadt Aschaffenburg  Landkreis Aschaffenburg	"	,
                                    "ABG-Landkreis Altenburger Land	"	,
                                    "ABI-Landkreis Anhalt-Bitterfeld	"	,
                                    "AC-Städteregion Aachen	"	,
                                    "AE-Vogtlandkreis	"	,
                                    "AH-Kreis Borken	"	,
                                    "AIB-Landkreis München  Landkreis Rosenheim	"	,
                                    "AIC-Landkreis Aichach-Friedberg	"	,
                                    "AK-Landkreis Altenkirchen (Westerwald)	"	,
                                    "ALF-Landkreis Hildesheim	"	,
                                    "ALZ-Landkreis Aschaffenburg	"	,
                                    "AM-Stadt Amberg	"	,
                                    "AN-Stadt Ansbach  Landkreis Ansbach	"	,
                                    "ANA-Erzgebirgskreis	"	,
                                    "ANG-Landkreis Uckermark	"	,
                                    "ANK-Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald	"	,
                                    "AÖ-Landkreis Altötting	"	,
                                    "AP-Landkreis Weimarer Land	"	,
                                    "APD-Landkreis Weimarer Land	"	,
                                    "ARN-Ilm-Kreis	"	,
                                    "ART-Kyffhäuserkreis	"	,
                                    "AS-Landkreis Amberg-Sulzbach	"	,
                                    "ASL-Salzlandkreis	"	,
                                    "ASZ-Erzgebirgskreis	"	,
                                    "AT-Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg	"	,
                                    "AU-Erzgebirgskreis	"	,
                                    "AUR-Landkreis Aurich	"	,
                                    "AW-Landkreis Ahrweiler	"	,
                                    "AZ-Landkreis Alzey-Worms	"	,
                                    "AZE-Landkreis Anhalt-Bitterfeld	"	,
                                    "B-Berlin	"	,
                                    "BA-Stadt Bamberg  Landkreis Bamberg	"	,
                                    "BAD-Stadt Baden-Baden	"	,
                                    "BAR-Landkreis Barnim	"	,
                                    "BB-Landkreis Böblingen	"	,
                                    "BBG-Salzlandkreis	"	,
                                    "BBL-Brandenburg  Landesregierung  Landtag und Polizei	"	,
                                    "BC-Landkreis Biberach	"	,
                                    "BCH-Neckar-Odenwald-Kreis	"	,
                                    "BD-Deutscher Bundestag  Bundesrat  Bundespräsidialamt  Bundesregierung  Bundesministerien  Bundesfinanzverwaltung und Bundesverfassungsgericht	"	,
                                    "BE-Kreis Warendorf	"	,
                                    "BED-Landkreis Mittelsachsen	"	,
                                    "BER-Landkreis Barnim	"	,
                                    "BF-Kreis Steinfurt	"	,
                                    "BGD-Landkreis Berchtesgadener Land	"	,
                                    "BGL-Landkreis Berchtesgadener Land	"	,
                                    "BH-Ortenaukreis  Landkreis Rastatt	"	,
                                    "BI-Stadt Bielefeld	"	,
                                    "BID-Landkreis Marburg-Biedenkopf	"	,
                                    "BIN-Landkreis Mainz-Bingen	"	,
                                    "BIR-Landkreis Birkenfeld	"	,
                                    "BIT-Eifelkreis Bitburg-Prüm	"	,
                                    "BIW-Landkreis Bautzen	"	,
                                    "BK-Landkreis Backnang	"	,
                                    "BKS-Landkreis Bernkastel-Wittlich	"	,
                                    "BL-Zollernalbkreis	"	,
                                    "BLB-Kreis Siegen-Wittgenstein	"	,
                                    "BLK-Burgenlandkreis	"	,
                                    "BM-Rhein-Erft-Kreis	"	,
                                    "BN-Stadt Bonn  Diplomaten	"	,
                                    "BNA-Landkreis Leipzig	"	,
                                    "BO-Stadt Bochum	"	,
                                    "BÖ-Landkreis Börde	"	,
                                    "BOG-Landkreis Straubing-Bogen	"	,
                                    "BOH-Kreis Borken	"	,
                                    "BOR-Kreis Borken	"	,
                                    "BOT-Stadt Bottrop	"	,
                                    "BP-Bundespolizei	"	,
                                    "BRA-Landkreis Wesermarsch	"	,
                                    "BRB-Stadt Brandenburg an der Havel	"	,
                                    "BRG-Landkreis Jerichower Land	"	,
                                    "BRK-Landkreis Bad Kissingen	"	,
                                    "BRL-Landkreis Goslar	"	,
                                    "BRV-Landkreis Rotenburg (Wümme)	"	,
                                    "BS-Stadt Braunschweig  Polizeidirektion Braunschweig (PD 100–9999)	"	,
                                    "BSB-Landkreis Osnabrück	"	,
                                    "BSK-Landkreis Oder-Spree	"	,
                                    "BT-Stadt Bayreuth  Landkreis Bayreuth	"	,
                                    "BTF-Landkreis Anhalt-Bitterfeld	"	,
                                    "BÜD-Wetteraukreis	"	,
                                    "BUL-Landkreis Amberg-Sulzbach (B  F und G 1–999)  Landkreis Schwandorf	"	,
                                    "BÜR-Kreis Paderborn	"	,
                                    "BÜS-Gemeinde Büsingen am Hochrhein (Gemeinde im Landkreis Konstanz  deutsche Exklave in der Schweiz) (A und Z 1–999)	"	,
                                    "BÜZ-Landkreis Rostock	"	,
                                    "BW-Wasserstraßen- und Schifffahrtsverwaltung des Bundes	"	,
                                    "BWL-Baden-Württemberg  Landesregierung  Landtag und Polizei	"	,
                                    "BYL-Bayern  Landesregierung und Landtag	"	,
                                    "BZ-Landkreis Bautzen	"	,
                                    "C-Stadt Chemnitz	"	,
                                    "CA-Landkreis Oberspreewald-Lausitz	"	,
                                    "CAS-Kreis Recklinghausen	"	,
                                    "CB-Stadt Cottbus	"	,
                                    "CE-Landkreis Celle	"	,
                                    "CHA-Landkreis Cham	"	,
                                    "CLP-Landkreis Cloppenburg	"	,
                                    "CLZ-Landkreis Goslar	"	,
                                    "CO-Stadt Coburg und Landkreis Coburg	"	,
                                    "COC-Landkreis Cochem-Zell	"	,
                                    "COE-Kreis Coesfeld	"	,
                                    "CR-Landkreis Schwäbisch Hall	"	,
                                    "CUX-Landkreis Cuxhaven	"	,
                                    "CW-Landkreis Calw	"	,
                                    "D-Stadt Düsseldorf	"	,
                                    "DA-Landkreis Darmstadt-Dieburg und Stadt Darmstadt	"	,
                                    "DAH-Landkreis Dachau	"	,
                                    "DAN-Landkreis Lüchow-Dannenberg	"	,
                                    "DAU-Landkreis Vulkaneifel	"	,
                                    "DBR-Landkreis Rostock	"	,
                                    "DD-Stadt Dresden  Polizei Sachsen (Q 1000–9999)	"	,
                                    "DE-Stadt Dessau-Roßlau	"	,
                                    "DEG-Landkreis Deggendorf	"	,
                                    "DEL-Stadt Delmenhorst	"	,
                                    "DGF-Landkreis Dingolfing-Landau	"	,
                                    "DH-Landkreis Diepholz	"	,
                                    "DI-Landkreis Darmstadt-Dieburg	"	,
                                    "DIL-Lahn-Dill-Kreis ohne die Stadt Wetzlar	"	,
                                    "DIN-Kreis Wesel	"	,
                                    "DIZ-Rhein-Lahn-Kreis	"	,
                                    "DKB-Landkreis Ansbach	"	,
                                    "DL-Landkreis Mittelsachsen	"	,
                                    "DLG-Landkreis Dillingen an der Donau	"	,
                                    "DM-Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg	"	,
                                    "DN-Kreis Düren	"	,
                                    "DO-Stadt Dortmund	"	,
                                    "DON-Landkreis Donau-Ries	"	,
                                    "DU-Stadt Duisburg	"	,
                                    "DUD-Landkreis Göttingen ohne die Stadt Göttingen	"	,
                                    "DÜW-Landkreis Bad Dürkheim	"	,
                                    "DW-Landkreis Sächsische Schweiz-Osterzgebirge	"	,
                                    "DZ-Landkreis Nordsachsen	"	,
                                    "E-Stadt Essen	"	,
                                    "EA-Stadt Eisenach	"	,
                                    "EB-Landkreis Nordsachsen	"	,
                                    "EBE-Landkreis Ebersberg	"	,
                                    "EBN-Landkreis Haßberge	"	,
                                    "EBS-Landkreis Forchheim  Landkreis Kulmbach (A–M 1–999)  Landkreis Bayreuth (N–Z 1–999)	"	,
                                    "ECK-Kreis Rendsburg-Eckernförde	"	,
                                    "ED-Landkreis Erding	"	,
                                    "EE-Landkreis Elbe-Elster	"	,
                                    "EF-Stadt Erfurt	"	,
                                    "EG-Landkreis Rottal-Inn	"	,
                                    "EH-Landkreis Oder-Spree	"	,
                                    "EI-Landkreis Eichstätt	"	,
                                    "EIC-Landkreis Eichsfeld	"	,
                                    "EIL-Landkreis Mansfeld-Südharz	"	,
                                    "EIN-Landkreis Northeim	"	,
                                    "EIS-Saale-Holzland-Kreis	"	,
                                    "EL-Landkreis Emsland	"	,
                                    "EM-Landkreis Emmendingen	"	,
                                    "EMD-Stadt Emden	"	,
                                    "EMS-Rhein-Lahn-Kreis	"	,
                                    "EN-Ennepe-Ruhr-Kreis	"	,
                                    "ER-Stadt Erlangen	"	,
                                    "ERB-Odenwaldkreis	"	,
                                    "ERH-Landkreis Erlangen-Höchstadt	"	,
                                    "ERK-Kreis Heinsberg	"	,
                                    "ERZ-Erzgebirgskreis	"	,
                                    "ES-Landkreis Esslingen	"	,
                                    "ESB-Landkreis Neustadt an der Waldnaab  Landkreis Amberg-Sulzbach (B  F  G  I  O und Q 1–999)  Landkreis Bayreuth (AT  BT  CT  DT  ... YT und ZT 1–99)  Landkreis Nürnberger Land (N 1–999)	"	,
                                    "ESW-Werra-Meißner-Kreis	"	,
                                    "EU-Kreis Euskirchen	"	,
                                    "EW-Landkreis Barnim	"	,
                                    "F-Stadt Frankfurt am Main	"	,
                                    "FB-Wetteraukreis	"	,
                                    "FD-Landkreis Fulda	"	,
                                    "FDB-Landkreis Aichach-Friedberg	"	,
                                    "FDS-Landkreis Freudenstadt	"	,
                                    "FEU-Landkreis Ansbach	"	,
                                    "FF-Stadt Frankfurt (Oder)	"	,
                                    "FFB-Landkreis Fürstenfeldbruck	"	,
                                    "FG-Landkreis Mittelsachsen	"	,
                                    "FI-Landkreis Elbe-Elster	"	,
                                    "FKB-Landkreis Waldeck-Frankenberg	"	,
                                    "FL-Stadt Flensburg	"	,
                                    "FLÖ-Landkreis Mittelsachsen	"	,
                                    "FN-Bodenseekreis	"	,
                                    "FO-Landkreis Forchheim	"	,
                                    "FOR-Landkreis Spree-Neiße	"	,
                                    "FR-Landkreis Breisgau-Hochschwarzwald  Stadt Freiburg im Breisgau (AA–MZ 100–999 und NA–ZZ 100–9999)	"	,
                                    "FRG-Landkreis Freyung-Grafenau	"	,
                                    "FRI-Landkreis Friesland	"	,
                                    "FRW-Landkreis Märkisch-Oderland	"	,
                                    "FS-Landkreis Freising	"	,
                                    "FT-Stadt Frankenthal (Pfalz)	"	,
                                    "FTL-Landkreis Sächsische Schweiz-Osterzgebirge	"	,
                                    "FÜ-Landkreis Fürth  Stadt Fürth (AA–ZZ 100–999)	"	,
                                    "FÜS-Landkreis Ostallgäu	"	,
                                    "FW-Landkreis Oder-Spree	"	,
                                    "FZ-Schwalm-Eder-Kreis	"	,
                                    "G-Stadt Gera	"	,
                                    "GA-Altmarkkreis Salzwedel	"	,
                                    "GAN-Landkreis Northeim	"	,
                                    "GAP-Landkreis Garmisch-Partenkirchen	"	,
                                    "GC-Landkreis Zwickau	"	,
                                    "GD-Ostalbkreis	"	,
                                    "GDB-Landkreis Nordwestmecklenburg	"	,
                                    "GE-Stadt Gelsenkirchen	"	,
                                    "GEL-Kreis Kleve	"	,
                                    "GEO-Landkreis Schweinfurt  Landkreis Haßberge (A und B 1000–9999)	"	,
                                    "GER-Landkreis Germersheim	"	,
                                    "GF-Landkreis Gifhorn	"	,
                                    "GG-Kreis Groß-Gerau	"	,
                                    "GHA-Landkreis Leipzig	"	,
                                    "GHC-Landkreis Wittenberg	"	,
                                    "GI-Landkreis Gießen	"	,
                                    "GK-Kreis Heinsberg	"	,
                                    "GL-Rheinisch-Bergischer Kreis	"	,
                                    "GLA-Kreis Recklinghausen	"	,
                                    "GM-Oberbergischer Kreis	"	,
                                    "GMN-Landkreis Vorpommern-Rügen ohne die Stadt Stralsund	"	,
                                    "GN-Main-Kinzig-Kreis ohne die Stadt Hanau	"	,
                                    "GNT-Landkreis Jerichower Land	"	,
                                    "GÖ-Landkreis Göttingen  Stadt Göttingen	"	,
                                    "GOA-Rhein-Hunsrück-Kreis	"	,
                                    "GOH-Rhein-Lahn-Kreis	"	,
                                    "GP-Landkreis Göppingen	"	,
                                    "GR-Landkreis Görlitz	"	,
                                    "GRA-Landkreis Freyung-Grafenau	"	,
                                    "GRH-Landkreis Meißen	"	,
                                    "GRI-Landkreis Rottal-Inn (B  I  O und Q 100–999)	"	,
                                    "GRM-Landkreis Leipzig	"	,
                                    "GRZ-Landkreis Greiz	"	,
                                    "GS-Landkreis Goslar	"	,
                                    "GT-Kreis Gütersloh	"	,
                                    "GTH-Landkreis Gotha	"	,
                                    "GÜ-Landkreis Rostock	"	,
                                    "GUB-Landkreis Spree-Neiße	"	,
                                    "GUN-Landkreis Weißenburg-Gunzenhausen	"	,
                                    "GV-Rhein-Kreis Neuss	"	,
                                    "GVM-Landkreis Nordwestmecklenburg	"	,
                                    "GW-Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald	"	,
                                    "GZ-Landkreis Günzburg	"	,
                                    "H-Region Hannover	"	,
                                    "HA-Stadt Hagen	"	,
                                    "HAB-Landkreis Bad Kissingen	"	,
                                    "HAL-Stadt Halle (Saale)	"	,
                                    "HAM-Stadt Hamm	"	,
                                    "HAS-Landkreis Haßberge	"	,
                                    "HB-Stadt Bremen  Senat und Bürgerschaft  Stadt Bremerhaven (A–Z 1000–9999)	"	,
                                    "HBN-Landkreis Hildburghausen	"	,
                                    "HBS-Landkreis Harz	"	,
                                    "HC-Landkreis Mittelsachsen	"	,
                                    "HCH-Zollernalbkreis  Landkreis Freudenstadt (YQ  QY  YV  VY und ZQ 100 bis 999)	"	,
                                    "HD-Stadt Heidelberg  Rhein-Neckar-Kreis (AA–ZZ 100–9999)	"	,
                                    "HDH-Landkreis Heidenheim	"	,
                                    "HDL-Landkreis Börde	"	,
                                    "HE-Landkreis Helmstedt	"	,
                                    "HEB-Landkreis Nürnberger Land	"	,
                                    "HEF-Landkreis Hersfeld-Rotenburg	"	,
                                    "HEI-Kreis Dithmarschen	"	,
                                    "HEL-Hessen  Landesregierung und Landtag	"	,
                                    "HER-Stadt Herne	"	,
                                    "HET-Landkreis Mansfeld-Südharz	"	,
                                    "HF-Kreis Herford	"	,
                                    "HG-Hochtaunuskreis	"	,
                                    "HGN-Landkreis Ludwigslust-Parchim	"	,
                                    "HGW-Stadt Greifswald (große kreisangehörige Stadt im Landkreis Vorpommern-Greifswald)	"	,
                                    "HH-Freie und Hansestadt Hamburg  Senat und Bürgerschaft	"	,
                                    "HHM-Burgenlandkreis	"	,
                                    "HI-Landkreis Hildesheim	"	,
                                    "HIG-Landkreis Eichsfeld	"	,
                                    "HIP-Landkreis Roth	"	,
                                    "HK-Landkreis Heidekreis	"	,
                                    "HL-Stadt Lübeck	"	,
                                    "HM-Landkreis Hameln-Pyrmont	"	,
                                    "HMÜ-Landkreis Göttingen ohne die Stadt Göttingen	"	,
                                    "HN-Stadt Heilbronn  Landkreis Heilbronn (AA–MZ 100–9999 und NA–ZZ 100–999)	"	,
                                    "HO-Stadt Hof  Landkreis Hof (AA–ZZ 100–9999)	"	,
                                    "HOG-Landkreis Kassel	"	,
                                    "HOH-Landkreis Haßberge	"	,
                                    "HOL-Landkreis Holzminden	"	,
                                    "HOM-Saarpfalz-Kreis ohne die Stadt St. Ingbert	"	,
                                    "HOR-Landkreis Freudenstadt	"	,
                                    "HÖS-Landkreis Erlangen-Höchstadt	"	,
                                    "HOT-Landkreis Zwickau	"	,
                                    "HP-Kreis Bergstraße	"	,
                                    "HR-Schwalm-Eder-Kreis	"	,
                                    "HRO-Stadt Rostock	"	,
                                    "HS-Kreis Heinsberg	"	,
                                    "HSK-Hochsauerlandkreis	"	,
                                    "HST-Stadt Stralsund (große kreisangehörige Stadt im Landkreis Vorpommern-Rügen)	"	,
                                    "HU-Stadt Hanau (Sonderstatusstadt im Main-Kinzig-Kreis)  Main-Kinzig-Kreis (übriges Kreisgebiet)	"	,
                                    "HV-Landkreis Stendal	"	,
                                    "HVL-Landkreis Havelland	"	,
                                    "HWI-Stadt Wismar (große kreisangehörige Stadt im Landkreis Nordwestmecklenburg)	"	,
                                    "HX-Kreis Höxter	"	,
                                    "HY-Landkreis Bautzen	"	,
                                    "HZ-Landkreis Harz	"	,
                                    "IGB-Stadt St. Ingbert (Mittelstadt im Saarpfalz-Kreis)	"	,
                                    "IK-Ilm-Kreis	"	,
                                    "IL-Ilm-Kreis	"	,
                                    "ILL-Landkreis Neu-Ulm	"	,
                                    "IN-Stadt Ingolstadt	"	,
                                    "IZ-Kreis Steinburg	"	,
                                    "J-Stadt Jena	"	,
                                    "JE-Landkreis Wittenberg	"	,
                                    "JL-Landkreis Jerichower Land	"	,
                                    "JÜL-Kreis Düren	"	,
                                    "K-Stadt Köln	"	,
                                    "KA-Landkreis Karlsruhe  Stadt Karlsruhe (AA–MZ 100–999 und NA–ZZ 100–9999)	"	,
                                    "KB-Landkreis Waldeck-Frankenberg	"	,
                                    "KC-Landkreis Kronach	"	,
                                    "KE-Stadt Kempten (Allgäu)	"	,
                                    "KEH-Landkreis Kelheim	"	,
                                    "KEL-Ortenaukreis	"	,
                                    "KEM-Landkreis Tirschenreuth  Landkreis Bayreuth (AT  BT  CT  DT  ... YT und ZT 1–99)	"	,
                                    "KF-Stadt Kaufbeuren	"	,
                                    "KG-Landkreis Bad Kissingen	"	,
                                    "KH-Landkreis Bad Kreuznach	"	,
                                    "KI-Stadt Kiel	"	,
                                    "KIB-Donnersbergkreis	"	,
                                    "KK-Kreis Viersen	"	,
                                    "KL-Stadt Kaiserslautern  Landkreis Kaiserslautern (AA–ZZ 100–999)	"	,
                                    "KLE-Kreis Kleve	"	,
                                    "KLZ-Altmarkkreis Salzwedel	"	,
                                    "KM-Landkreis Bautzen	"	,
                                    "KN-Landkreis Konstanz ohne die Gemeinde Büsingen am Hochrhein	"	,
                                    "KO-Stadt Koblenz	"	,
                                    "KÖN-Landkreis Rhön-Grabfeld	"	,
                                    "KÖT-Landkreis Anhalt-Bitterfeld	"	,
                                    "KÖZ-Landkreis Cham	"	,
                                    "KR-Stadt Krefeld	"	,
                                    "KRU-Landkreis Günzburg	"	,
                                    "KS-Landkreis Kassel und Stadt Kassel	"	,
                                    "KT-Landkreis Kitzingen	"	,
                                    "KU-Landkreis Kulmbach	"	,
                                    "KÜN-Hohenlohekreis	"	,
                                    "KUS-Landkreis Kusel	"	,
                                    "KW-Landkreis Dahme-Spreewald	"	,
                                    "KY-Landkreis Ostprignitz-Ruppin	"	,
                                    "KYF-Kyffhäuserkreis	"	,
                                    "L-Sachsen	"	,
                                    "LA-Stadt Landshut  Landkreis Landshut (AA–ZZ 100–999 und 5000–9999)	"	,
                                    "LAN-Landkreis Dingolfing-Landau	"	,
                                    "LAU-Landkreis Nürnberger Land	"	,
                                    "LB-Landkreis Ludwigsburg	"	,
                                    "LBS-Saale-Orla-Kreis	"	,
                                    "LBZ-Landkreis Ludwigslust-Parchim	"	,
                                    "LC-Landkreis Dahme-Spreewald	"	,
                                    "LD-Stadt Landau in der Pfalz	"	,
                                    "LDK-Lahn-Dill-Kreis ohne die Stadt Wetzlar	"	,
                                    "LDS-Landkreis Dahme-Spreewald	"	,
                                    "LEO-Landkreis Böblingen	"	,
                                    "LER-Landkreis Leer	"	,
                                    "LEV-Stadt Leverkusen	"	,
                                    "LF-Landkreis Berchtesgadener Land  Landkreis Altötting (C 1–999  E 1–500  I  J  M  O  Q und V 1–999)  Landkreis Traunstein (B  F und G 1–999  DH 1–100  FZ  GH und KQ 1–999  LU 1–200  RW 1–999  TK 1–100  TS 1–999  VW 200–400 sowie WW  XX und ZZ 1–999)	"	,
                                    "LG-Landkreis Lüneburg	"	,
                                    "LH-Kreis Coesfeld  Kreis Unna	"	,
                                    "LI-Landkreis Lindau (Bodensee)	"	,
                                    "LIB-Landkreis Elbe-Elster	"	,
                                    "LIF-Landkreis Lichtenfels	"	,
                                    "LIP-Kreis Lippe	"	,
                                    "LL-Landkreis Landsberg am Lech	"	,
                                    "LM-Landkreis Limburg-Weilburg	"	,
                                    "LN-Landkreis Dahme-Spreewald	"	,
                                    "LÖ-Landkreis Lörrach	"	,
                                    "LÖB-Landkreis Görlitz	"	,
                                    "LOS-Landkreis Oder-Spree	"	,
                                    "LP-Kreis Soest	"	,
                                    "LR-Ortenaukreis	"	,
                                    "LRO-Landkreis Rostock	"	,
                                    "LSA-Sachsen-Anhalt  Landesregierung  Landtag und Polizei	"	,
                                    "LSN-Sachsen  Landesregierung und Landtag	"	,
                                    "LSZ-Unstrut-Hainich-Kreis	"	,
                                    "LU-Stadt Ludwigshafen am Rhein	"	,
                                    "LÜN-Kreis Unna	"	,
                                    "LUP-Landkreis Ludwigslust-Parchim	"	,
                                    "LWL-Landkreis Ludwigslust-Parchim	"	,
                                    "M-Landkreis München  Stadt München (AA–ZZ 100–9999)	"	,
                                    "MA-Stadt Mannheim	"	,
                                    "MAB-Erzgebirgskreis	"	,
                                    "MAI-Landkreis Kelheim  Landkreis Landshut (B  F  G  I  O und Q 1–9999)	"	,
                                    "MAK-Landkreis Wunsiedel im Fichtelgebirge	"	,
                                    "MAL-Landkreis Landshut (B  F  G  I  O und Q 1–9999)	"	,
                                    "MB-Landkreis Miesbach	"	,
                                    "MC-Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg	"	,
                                    "MD-Stadt Magdeburg	"	,
                                    "ME-Kreis Mettmann	"	,
                                    "MED-Kreis Dithmarschen	"	,
                                    "MEG-Schwalm-Eder-Kreis	"	,
                                    "MEI-Landkreis Meißen	"	,
                                    "MEK-Erzgebirgskreis	"	,
                                    "MEL-Landkreis Osnabrück	"	,
                                    "MER-Saalekreis	"	,
                                    "MET-Landkreis Rhön-Grabfeld	"	,
                                    "MG-Stadt Mönchengladbach	"	,
                                    "MGH-Main-Tauber-Kreis	"	,
                                    "MGN-Landkreis Schmalkalden-Meiningen	"	,
                                    "MH-Stadt Mülheim an der Ruhr	"	,
                                    "MHL-Unstrut-Hainich-Kreis	"	,
                                    "MI-Kreis Minden-Lübbecke	"	,
                                    "MIL-Landkreis Miltenberg	"	,
                                    "MK-Märkischer Kreis	"	,
                                    "MKK-Main-Kinzig-Kreis ohne die Stadt Hanau	"	,
                                    "ML-Landkreis Mansfeld-Südharz	"	,
                                    "MM-Stadt Memmingen	"	,
                                    "MN-Landkreis Unterallgäu	"	,
                                    "MO-Kreis Wesel	"	,
                                    "MOD-Landkreis Ostallgäu	"	,
                                    "MOL-Landkreis Märkisch-Oderland	"	,
                                    "MON-Städteregion Aachen  Kreis Düren	"	,
                                    "MOS-Neckar-Odenwald-Kreis	"	,
                                    "MQ-Saalekreis	"	,
                                    "MR-Landkreis Marburg-Biedenkopf	"	,
                                    "MS-Stadt Münster	"	,
                                    "MSE-Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg	"	,
                                    "MSH-Landkreis Mansfeld-Südharz	"	,
                                    "MSP-Landkreis Main-Spessart	"	,
                                    "MST-Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg	"	,
                                    "MTK-Main-Taunus-Kreis	"	,
                                    "MTL-Landkreis Leipzig	"	,
                                    "MÜ-Landkreis Mühldorf am Inn	"	,
                                    "MÜB-Landkreis Hof  Landkreis Bayreuth (A–M 100–999 und N–Z 1–99)	"	,
                                    "MÜR-Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg	"	,
                                    "MVL-Mecklenburg-Vorpommern  Landesregierung  Landtag und Polizei	"	,
                                    "MW-Landkreis Mittelsachsen	"	,
                                    "MY-Landkreis Mayen-Koblenz	"	,
                                    "MYK-Landkreis Mayen-Koblenz	"	,
                                    "MZ-Landkreis Mainz-Bingen  Stadt Mainz (AA–KY 100–9999 und LA–ZZ 100–999)	"	,
                                    "MZG-Landkreis Merzig-Wadern	"	,
                                    "N-Landkreis Nürnberger Land (A–Z 1–999)  Stadt Nürnberg (A–Z 1000–9999 und AA–ZZ 100–9999)	"	,
                                    "NAB-Landkreis Schwandorf  Landkreis Amberg-Sulzbach (B  F und G 1–999)	"	,
                                    "NAI-Landkreis Hof	"	,
                                    "NAU-Landkreis Havelland	"	,
                                    "NB-Stadt Neubrandenburg (große kreisangehörige Stadt im Landkreis Mecklenburgische Seenplatte)	"	,
                                    "ND-Landkreis Neuburg-Schrobenhausen	"	,
                                    "NDH-Landkreis Nordhausen	"	,
                                    "NE-Rhein-Kreis Neuss	"	,
                                    "NEA-Landkreis Neustadt an der Aisch-Bad Windsheim	"	,
                                    "NEB-Burgenlandkreis	"	,
                                    "NEC-Stadt Coburg und Landkreis Coburg	"	,
                                    "NEN-Landkreis Schwandorf	"	,
                                    "NES-Landkreis Rhön-Grabfeld	"	,
                                    "NEW-Landkreis Neustadt an der Waldnaab	"	,
                                    "NF-Kreis Nordfriesland	"	,
                                    "NH-Landkreis Sonneberg	"	,
                                    "NI-Landkreis Nienburg/Weser	"	,
                                    "NK-Landkreis Neunkirchen	"	,
                                    "NL-Niedersachsen  Landesregierung und Landtag	"	,
                                    "NM-Landkreis Neumarkt in der Oberpfalz	"	,
                                    "NMB-Burgenlandkreis	"	,
                                    "NMS-Stadt Neumünster	"	,
                                    "NÖ-Landkreis Donau-Ries	"	,
                                    "NOH-Landkreis Grafschaft Bentheim	"	,
                                    "NOL-Landkreis Görlitz	"	,
                                    "NOM-Landkreis Northeim	"	,
                                    "NOR-Landkreis Aurich	"	,
                                    "NP-Landkreis Ostprignitz-Ruppin	"	,
                                    "NR-Landkreis Neuwied	"	,
                                    "NRW-Nordrhein-Westfalen  Landesregierung  Landtag und Polizei	"	,
                                    "NT-Landkreis Esslingen	"	,
                                    "NU-Landkreis Neu-Ulm	"	,
                                    "NVP-Landkreis Vorpommern-Rügen ohne die Stadt Stralsund	"	,
                                    "NW-Stadt Neustadt an der Weinstraße	"	,
                                    "NWM-Landkreis Nordwestmecklenburg ohne die Stadt Wismar	"	,
                                    "NY-Landkreis Görlitz	"	,
                                    "NZ-Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg	"	,
                                    "OA-Landkreis Oberallgäu	"	,
                                    "OAL-Landkreis Ostallgäu	"	,
                                    "OB-Stadt Oberhausen	"	,
                                    "OBB-Landkreis Miltenberg	"	,
                                    "OBG-Landkreis Stendal	"	,
                                    "OC-Landkreis Börde	"	,
                                    "OCH-Landkreis Würzburg	"	,
                                    "OD-Kreis Stormarn	"	,
                                    "OE-Kreis Olpe	"	,
                                    "OF-Landkreis Offenbach und Stadt Offenbach am Main	"	,
                                    "OG-Ortenaukreis	"	,
                                    "OH-Kreis Ostholstein	"	,
                                    "OHA-Landkreis Göttingen	"	,
                                    "ÖHR-Hohenlohekreis	"	,
                                    "OHV-Landkreis Oberhavel	"	,
                                    "OHZ-Landkreis Osterholz	"	,
                                    "OK-Landkreis Börde	"	,
                                    "OL-Landkreis Oldenburg  Stadt Oldenburg (AA–ZZ 100–999)	"	,
                                    "OP-Stadt Leverkusen	"	,
                                    "OPR-Landkreis Ostprignitz-Ruppin	"	,
                                    "OS-Stadt Osnabrück  Landkreis Osnabrück (AA–ZZ 100–999)	"	,
                                    "OSL-Landkreis Oberspreewald-Lausitz	"	,
                                    "OTW-Landkreis Ottweiler	"	,
                                    "OVI-Landkreis Schwandorf	"	,
                                    "OVL-Vogtlandkreis	"	,
                                    "OVP-Landkreis Ostvorpommern	"	,
                                    "OZ-Landkreis Nordsachsen	"	,
                                    "P-Stadt Potsdam	"	,
                                    "PA-Stadt Passau (A–Z 1–9999)  Landkreis Passau (AA–ZZ 1–999)	"	,
                                    "PAF-Landkreis Pfaffenhofen an der Ilm	"	,
                                    "PAN-Landkreis Rottal-Inn	"	,
                                    "PAR-Landkreis Neumarkt in der Oberpfalz  Landkreis Kelheim (Q  Y  BB und CC 1–999)	"	,
                                    "PB-Kreis Paderborn	"	,
                                    "PCH-Landkreis Ludwigslust-Parchim	"	,
                                    "PE-Landkreis Peine	"	,
                                    "PEG-Landkreis Forchheim  Landkreis Nürnberger Land (A 1–999)  Landkreis Bayreuth (B–Z 1–999)	"	,
                                    "PF-Enzkreis  Stadt Pforzheim (AA–MZ 100–999 und NA–ZZ 100–9999)	"	,
                                    "PI-Kreis Pinneberg	"	,
                                    "PIR-Landkreis Sächsische Schweiz-Osterzgebirge	"	,
                                    "PL-Vogtlandkreis	"	,
                                    "PLÖ-Kreis Plön	"	,
                                    "PM-Landkreis Potsdam-Mittelmark	"	,
                                    "PN-Saale-Orla-Kreis	"	,
                                    "PR-Landkreis Prignitz	"	,
                                    "PRÜ-Eifelkreis Bitburg-Prüm	"	,
                                    "PS-Stadt Pirmasens (A–Z 1–9999)  Landkreis Südwestpfalz (AA–ZZ 1–999)	"	,
                                    "PW-Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald	"	,
                                    "PZ-Landkreis Uckermark	"	,
                                    "QFT-Saalekreis	"	,
                                    "QLB-Landkreis Harz	"	,
                                    "R-Landkreis Regensburg  Stadt Regensburg (AA–MM 1–999 und MN–ZZ 1000–9999)	"	,
                                    "RA-Landkreis Rastatt	"	,
                                    "RC-Vogtlandkreis	"	,
                                    "RD-Kreis Rendsburg-Eckernförde	"	,
                                    "RDG-Landkreis Vorpommern-Rügen ohne die Stadt Stralsund	"	,
                                    "RE-Kreis Recklinghausen	"	,
                                    "REG-Landkreis Regen	"	,
                                    "REH-Landkreis Hof  Landkreis Wunsiedel im Fichtelgebirge (A  E  F  H  J  M  N  P  R  S  V und X 1–999  AA  FF  GG  OO und ZZ 100–999 sowie AU 900–999)	"	,
                                    "REI-Landkreis Berchtesgadener Land	"	,
                                    "RG-Landkreis Meißen	"	,
                                    "RH-Landkreis Roth	"	,
                                    "RI-Landkreis Schaumburg	"	,
                                    "RID-Landkreis Kelheim	"	,
                                    "RIE-Landkreis Meißen	"	,
                                    "RL-Landkreis Mittelsachsen	"	,
                                    "RM-Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg	"	,
                                    "RN-Landkreis Havelland	"	,
                                    "RO-Stadt Rosenheim  Landkreis Rosenheim (AA–ZZ 100–9999)	"	,
                                    "ROD-Landkreis Cham  Landkreis Schwandorf (B 1–500  F 1–700  G 50–400 und I 100–1000)	"	,
                                    "ROF-Landkreis Hersfeld-Rotenburg	"	,
                                    "ROK-Donnersbergkreis	"	,
                                    "ROL-Landkreis Landshut   Landkreis Kelheim (A bis Z)	"	,
                                    "ROS-Landkreis Rostock	"	,
                                    "ROT-Landkreis Ansbach	"	,
                                    "ROW-Landkreis Rotenburg (Wümme)	"	,
                                    "RP-Rhein-Pfalz-Kreis	"	,
                                    "RPL-Rheinland-Pfalz  Landesregierung  Landtag und Polizei	"	,
                                    "RS-Stadt Remscheid	"	,
                                    "RSL-Stadt Dessau-Roßlau	"	,
                                    "RT-Landkreis Reutlingen	"	,
                                    "RU-Landkreis Saalfeld-Rudolstadt	"	,
                                    "RÜD-Rheingau-Taunus-Kreis	"	,
                                    "RÜG-Landkreis Vorpommern-Rügen	"	,
                                    "RV-Landkreis Ravensburg	"	,
                                    "RW-Landkreis Rottweil	"	,
                                    "RZ-Kreis Herzogtum Lauenburg	"	,
                                    "S-Stadt Stuttgart	"	,
                                    "SAB-Landkreis Trier-Saarburg	"	,
                                    "SAD-Landkreis Schwandorf	"	,
                                    "SAL-Saarland  Landesregierung  Landtag und Polizei	"	,
                                    "SAN-Landkreis Hof (W–Z 1–999)  Landkreis Kulmbach (A–R 1–9999 und JA–ZZ 1–999)  Landkreis Kronach (S–V 1–9999 und AA–IZ 1–999)	"	,
                                    "SAW-Altmarkkreis Salzwedel	"	,
                                    "SÄK-Landkreis Säckingen	"	,
                                    "SB-Regionalverband Saarbrücken ohne die Stadt Völklingen	"	,
                                    "SBG-Landkreis Vorpommern-Greifswald	"	,
                                    "SBK-Salzlandkreis	"	,
                                    "SC-Stadt Schwabach	"	,
                                    "SCZ-Saale-Orla-Kreis	"	,
                                    "SDH-Kyffhäuserkreis	"	,
                                    "SDL-Landkreis Stendal	"	,
                                    "SDT-Landkreis Uckermark	"	,
                                    "SE-Kreis Segeberg	"	,
                                    "SEB-Landkreis Sächsische Schweiz-Osterzgebirge	"	,
                                    "SEE-Landkreis Märkisch-Oderland	"	,
                                    "SEF-Landkreis Neustadt an der Aisch-Bad Windsheim	"	,
                                    "SEL-Landkreis Wunsiedel im Fichtelgebirge	"	,
                                    "SFB-Landkreis Oberspreewald-Lausitz	"	,
                                    "SFT-Salzlandkreis	"	,
                                    "SG-Stadt Solingen	"	,
                                    "SGH-Landkreis Mansfeld-Südharz	"	,
                                    "SH-Schleswig-Holstein  Landesregierung  Landtag und Polizei	"	,
                                    "SHA-Landkreis Schwäbisch Hall	"	,
                                    "SHG-Landkreis Schaumburg	"	,
                                    "SHK-Saale-Holzland-Kreis	"	,
                                    "SHL-Stadt Suhl	"	,
                                    "SI-Kreis Siegen-Wittgenstein	"	,
                                    "SIG-Landkreis Sigmaringen	"	,
                                    "SIH-fiktiver Ort	"	,
                                    "SIM-Rhein-Hunsrück-Kreis	"	,
                                    "SK-Saalekreis	"	,
                                    "SL-Kreis Schleswig-Flensburg	"	,
                                    "SLE-Kreis Düren  Kreis Euskirchen	"	,
                                    "SLF-Landkreis Saalfeld-Rudolstadt	"	,
                                    "SLG-Landkreis Saulgau	"	,
                                    "SLK-Salzlandkreis	"	,
                                    "SLN-Landkreis Altenburger Land	"	,
                                    "SLS-Landkreis Saarlouis	"	,
                                    "SLÜ-Main-Kinzig-Kreis ohne die Stadt Hanau	"	,
                                    "SLZ-Wartburgkreis	"	,
                                    "SM-Landkreis Schmalkalden-Meiningen	"	,
                                    "SMÜ-Landkreis Augsburg	"	,
                                    "SN-Stadt Schwerin	"	,
                                    "SO-Kreis Soest	"	,
                                    "SOB-Landkreis Neuburg-Schrobenhausen	"	,
                                    "SOG-Landkreis Weilheim-Schongau	"	,
                                    "SOK-Saale-Orla-Kreis	"	,
                                    "SÖM-Landkreis Sömmerda	"	,
                                    "SON-Landkreis Sonneberg	"	,
                                    "SP-Stadt Speyer	"	,
                                    "SPB-Landkreis Spree-Neiße	"	,
                                    "SPN-Landkreis Spree-Neiße	"	,
                                    "SR-Stadt Straubing (A–Z 1–9999)  Landkreis Straubing-Bogen (AA–ZZ 1–999)	"	,
                                    "SRB-Landkreis Märkisch-Oderland	"	,
                                    "SRO-Saale-Holzland-Kreis	"	,
                                    "ST-Kreis Steinfurt	"	,
                                    "STA-Landkreis Starnberg	"	,
                                    "STB-Landkreis Ludwigslust-Parchim	"	,
                                    "STD-Landkreis Stade	"	,
                                    "STE-Landkreis Lichtenfels	"	,
                                    "STL-Erzgebirgskreis	"	,
                                    "STO-Landkreis Stockach	"	,
                                    "SU-Rhein-Sieg-Kreis	"	,
                                    "SUL-Landkreis Amberg-Sulzbach	"	,
                                    "SÜW-Landkreis Südliche Weinstraße	"	,
                                    "SW-Stadt Schweinfurt  Landkreis Schweinfurt (AA–ZZ 100–9999)	"	,
                                    "SWA-Rheingau-Taunus-Kreis	"	,
                                    "SY-Landkreis Diepholz	"	,
                                    "SZ-Stadt Salzgitter	"	,
                                    "SZB-Erzgebirgskreis	"	,
                                    "TBB-Main-Tauber-Kreis	"	,
                                    "TDO-Landkreis Nordsachsen	"	,
                                    "TE-Kreis Steinfurt	"	,
                                    "TET-Landkreis Rostock	"	,
                                    "TF-Landkreis Teltow-Fläming	"	,
                                    "TG-Landkreis Nordsachsen	"	,
                                    "THL-Thüringen  Landesregierung und Landtag	"	,
                                    "THW-Bundesanstalt Technisches Hilfswerk	"	,
                                    "TIR-Landkreis Tirschenreuth	"	,
                                    "TO-Landkreis Nordsachsen	"	,
                                    "TÖL-Landkreis Bad Tölz-Wolfratshausen	"	,
                                    "TP-Landkreis Uckermark	"	,
                                    "TR-Landkreis Trier-Saarburg und Stadt Trier	"	,
                                    "TS-Landkreis Traunstein	"	,
                                    "TT-Bodenseekreis	"	,
                                    "TÜ-Landkreis Tübingen	"	,
                                    "TUT-Landkreis Tuttlingen	"	,
                                    "UE-Landkreis Uelzen	"	,
                                    "UEM-Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald	"	,
                                    "UFF-Landkreis Neustadt an der Aisch-Bad Windsheim	"	,
                                    "UH-Unstrut-Hainich-Kreis	"	,
                                    "UL-Stadt Ulm  Alb-Donau-Kreis (AA–MZ 100–999 und NA–ZZ 100–9999)	"	,
                                    "UM-Landkreis Uckermark	"	,
                                    "UN-Kreis Unna	"	,
                                    "USI-Hochtaunuskreis	"	,
                                    "ÜB-Bodenseekreis  Landkreis Ravensburg	"	,
                                    "V-Vogtlandkreis	"	,
                                    "VAI-Landkreis Ludwigsburg	"	,
                                    "VB-Vogelsbergkreis	"	,
                                    "VEC-Landkreis Vechta	"	,
                                    "VER-Landkreis Verden	"	,
                                    "VG-Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald	"	,
                                    "VIB-Landkreis Landshut  Landkreis Rottal-Inn (B  I  O und Q 100–999)	"	,
                                    "VIE-Kreis Viersen	"	,
                                    "VIT-Landkreis Regen	"	,
                                    "VK-Stadt Völklingen (Mittelstadt im Regionalverband Saarbrücken)	"	,
                                    "VOH-Landkreis Neustadt an der Waldnaab	"	,
                                    "VR-Landkreis Vorpommern-Rügen ohne die Stadt Stralsund	"	,
                                    "VS-Schwarzwald-Baar-Kreis	"	,
                                    "W-Stadt Wuppertal	"	,
                                    "WA-Landkreis Waldeck-Frankenberg	"	,
                                    "WAF-Kreis Warendorf	"	,
                                    "WAK-Wartburgkreis	"	,
                                    "WAN-Stadt Herne	"	,
                                    "WAR-Kreis Höxter	"	,
                                    "WAT-Stadt Bochum	"	,
                                    "WB-Landkreis Wittenberg	"	,
                                    "WBS-Landkreis Eichsfeld	"	,
                                    "WDA-Landkreis Zwickau	"	,
                                    "WE-Stadt Weimar	"	,
                                    "WEL-Landkreis Limburg-Weilburg	"	,
                                    "WEN-Stadt Weiden in der Oberpfalz	"	,
                                    "WER-Landkreis Dillingen an der Donau  Landkreis Augsburg (A–Z 7000–9999 und YA–YZ 1–999)	"	,
                                    "WES-Kreis Wesel	"	,
                                    "WF-Landkreis Wolfenbüttel	"	,
                                    "WG-Landkreis Ravensburg	"	,
                                    "WHV-Stadt Wilhelmshaven	"	,
                                    "WI-Stadt Wiesbaden	"	,
                                    "WIL-Landkreis Bernkastel-Wittlich	"	,
                                    "WIN-Winden (fiktiver Ort)	"	,
                                    "WIS-Landkreis Nordwestmecklenburg	"	,
                                    "WIT-Ennepe-Ruhr-Kreis	"	,
                                    "WIV-fiktiver Ort	"	,
                                    "WIZ-Werra-Meißner-Kreis	"	,
                                    "WK-Landkreis Ostprignitz-Ruppin	"	,
                                    "WL-Landkreis Harburg	"	,
                                    "WLG-Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald	"	,
                                    "WM-Landkreis Weilheim-Schongau	"	,
                                    "WMS-Landkreis Börde	"	,
                                    "WN-Rems-Murr-Kreis	"	,
                                    "WND-Landkreis St. Wendel	"	,
                                    "WO-Stadt Worms	"	,
                                    "WOB-Stadt Wolfsburg	"	,
                                    "WOH-Landkreis Kassel	"	,
                                    "WOL-Ortenaukreis  Landkreis Freudenstadt (A bis E 9000–9999)	"	,
                                    "WOR-Landkreis Bad Tölz-Wolfratshausen  Landkreis München (F und O 10–9999)  Landkreis Starnberg (B und G 10–9999)	"	,
                                    "WOS-Landkreis Freyung-Grafenau	"	,
                                    "WR-Landkreis Harz	"	,
                                    "WRN-Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg	"	,
                                    "WS-Landkreis Rosenheim	"	,
                                    "WSF-Burgenlandkreis	"	,
                                    "WST-Landkreis Ammerland	"	,
                                    "WSW-Landkreis Görlitz	"	,
                                    "WT-Landkreis Waldshut	"	,
                                    "WTL-Landkreis Osnabrück	"	,
                                    "WTM-Landkreis Wittmund	"	,
                                    "WÜ-Landkreis Würzburg  Stadt Würzburg (AA–NZ 100–9999 und OA–ZZ 100–999)	"	,
                                    "WUG-Landkreis Weißenburg-Gunzenhausen	"	,
                                    "WÜM-Landkreis Cham	"	,
                                    "WUN-Landkreis Wunsiedel im Fichtelgebirge	"	,
                                    "WUR-Landkreis Leipzig	"	,
                                    "WW-Westerwaldkreis	"	,
                                    "WZ-Stadt Wetzlar (Sonderstatusstadt im Lahn-Dill-Kreis)	"	,
                                    "WZL-Landkreis Börde	"	,
                                    "X-Internationale Hauptquartiere (NATO)	"	,
                                    "Y-Bundeswehr	"	,
                                    "Z-Landkreis Zwickau	"	,
                                    "ZE-Landkreis Anhalt-Bitterfeld	"	,
                                    "ZEL-Landkreis Cochem-Zell	"	,
                                    "ZI-Landkreis Görlitz	"	,
                                    "ZIG-Schwalm-Eder-Kreis	"	,
                                    "ZP-Erzgebirgskreis	"	,
                                    "ZR-Landkreis Greiz	"	,
                                    "ZW-Stadt Zweibrücken  Landkreis Südwestpfalz (AA–ZZ 1–99)	"	,
                                    "ZZ-Burgenlandkreis	"};


int main(void){
    char eingabe[11]="";
    char check[]="-";
    char *pEingabe;
    char *pKennzeichen;

    int x,i;

    printf("Kennzeichen eingeben...........: ");
    scanf("%10[^\n]",eingabe);
    while (getchar()!='\n') {}

    for(i=0;i<strlen(eingabe);++i){
        eingabe[i] = toupper(eingabe[i]);
    }

    pEingabe = strtok(eingabe, check);
    
    for (x=0; x<723; ++x) {
        pKennzeichen = strtok(kennzeichen[x], check);
        
        if (strcmp(pEingabe,pKennzeichen)==0) {
            pKennzeichen = strtok(NULL, check);
            printf("Landkreis oder kreisfreie Stadt: %s\n",pKennzeichen);
            break;
        }
        else if (x==722) {
            printf("Ungültige Kennzeichen!\n");
        }
    }
    /*
    Kennzeichen eingeben...........: PB-XY 1234
    Landkreis oder kreisfreie Stadt: Paderborn

    */
    return 0;
}